# Generated by Django 3.1.6 on 2021-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='periodsandmovements',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
    ]
