# Generated by Django 3.1.6 on 2021-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210520_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodsandmovements',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
